### ISSUE TITLE
Party Mode spinner sometimes crashes the client

### ISSUE THREAD

**Issue by robere2** [bugfroggy/Quickplay2.0#37]
If a user has the spinner GUI open, the sounds that it play can crash the client occasionally. Exact cause is unclear but I do know that I'm doing something wrong with how I'm implementing sounds. Unclear if affected versions are 1.8.8-1.8.9, 1.9+, or both.

Crash report:
```---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 3/18/18 8:37 PM
Description: Unexpected error

java.util.ConcurrentModificationException
    at com.google.common.collect.HashBiMap$Itr.checkForConcurrentModification(HashBiMap.java:339)
    at com.google.common.collect.HashBiMap$Itr.hasNext(HashBiMap.java:345)
    at net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:222)
    at net.minecraft.client.audio.SoundHandler.func_73660_a(SourceFile:195)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2100)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at com.google.common.collect.HashBiMap$Itr.checkForConcurrentModification(HashBiMap.java:339)
    at com.google.common.collect.HashBiMap$Itr.hasNext(HashBiMap.java:345)
    at net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:222)
    at net.minecraft.client.audio.SoundHandler.func_73660_a(SourceFile:195)
```

**Comment by robere2** [comment]
After some testing I believe this issue is fixed. Re-open if occurs again.
